[build-system]
requires = ["setuptools>=78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "gamenet-uq"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "ase",
  "torch >= 2.4.",
  "torch-geometric >= 2.5",
  "networkx",
  "scikit-learn", 
  "matplotlib", 
  "scipy"
  "numpy"
]

authors = [
  {name = "Santiago Morandi", email = "santiagomorandi@yahoo.it"}
]
maintainers = [
  {name = "Santiago Morandi", email = "santiagomorandi@yahoo.it"}
]
description = "Graph Neural Network with uncertainty quantification for adsorption energy prediction"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["heterogeneous catalysis", "adsorption energy", "kinetics", "machine learning", "transition metals"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.12"
]

[project.optional-dependencies]
dev = ["pytest", 
       "pytest-cov", 
       "coverage", 
       "codecov", 
       "flake8"
]

[project.urls]
Repository = "https://github.com/LopezGroup-ICIQ/gamenet_uq"
Bugtracker = "https://github.com/LopezGroup-ICIQ/gamenet_uq/issues"

[project.scripts]

[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--import-mode=importlib",
    "-v",
]
testpaths = [
    "tests",
]
pythonpath = "src"
